// <auto-generated />
using System;
using GGData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GGData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            Microsoft.EntityFrameworkCore.SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GGData.Models.Avaliacao", b =>
            {
                b.Property<int>("AvaliacaoId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                Microsoft.EntityFrameworkCore.SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvaliacaoId"));

                b.Property<string>("Comentarios")
                    .HasMaxLength(5000)
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("DataReview")
                    .HasColumnType("datetime2");

                b.Property<int>("JogoId")
                    .HasColumnType("int");

                b.Property<int>("Nota")
                    .HasColumnType("int");

                b.Property<string>("TipoUsuario")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<int>("UsuarioId")
                    .HasColumnType("int");

                b.HasKey("AvaliacaoId");

                b.HasIndex("JogoId");

                b.HasIndex("UsuarioId");

                b.ToTable("Avaliacao");
            });

            modelBuilder.Entity("GGData.Models.Estatistica", b =>
            {
                b.Property<int>("EstatisticaId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                Microsoft.EntityFrameworkCore.SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstatisticaId"));

                b.Property<string>("Conquistas")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("JogoId")
                    .HasColumnType("int");

                b.Property<decimal>("MediaNotaCriticos")
                    .HasPrecision(5, 2)
                    .HasColumnType("decimal(5,2)");

                b.Property<decimal>("MediaNotaUtilizadores")
                    .HasPrecision(5, 2)
                    .HasColumnType("decimal(5,2)");

                b.Property<decimal>("TempoMedioJogo")
                    .HasPrecision(10, 2)
                    .HasColumnType("decimal(10,2)");

                b.Property<int>("TotalAvaliacoes")
                    .HasColumnType("int");

                b.HasKey("EstatisticaId");

                b.HasIndex("JogoId")
                    .IsUnique();

                b.ToTable("Estatistica");
            });

            modelBuilder.Entity("GGData.Models.Jogo", b =>
            {
                b.Property<int>("JogoId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                Microsoft.EntityFrameworkCore.SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JogoId"));

                b.Property<DateTime>("DataLancamento")
                    .HasColumnType("datetime2");

                b.Property<string>("Genero")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("ImagemUrl")
                    .HasMaxLength(300)
                    .HasColumnType("nvarchar(300)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Plataforma")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("UtilizadorId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("JogoId");

                b.HasIndex("UtilizadorId");

                b.ToTable("Jogos");
            });

            modelBuilder.Entity("GGData.Models.Usuarios", b =>
            {
                b.Property<int>("UsuarioId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                Microsoft.EntityFrameworkCore.SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                b.Property<DateTime>("DataRegistro")
                    .HasColumnType("datetime2");

                b.Property<string>("DescricaoProfissional")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Instituicao")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("Senha")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TipoUsuario")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("WebsiteProfissional")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UsuarioId");

                b.ToTable("Usuarios");
            });

            // Identity related entities (roles, claims, users, etc) omitted for brevity, 
            // mas deve ser igual ao original corrigido

            // Relações

            modelBuilder.Entity("GGData.Models.Avaliacao", b =>
            {
                b.HasOne("GGData.Models.Jogo", "Jogo")
                    .WithMany("Avaliacoes")
                    .HasForeignKey("JogoId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("GGData.Models.Usuarios", "Usuario")
                    .WithMany("Avaliacoes")
                    .HasForeignKey("UsuarioId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Jogo");

                b.Navigation("Usuario");
            });

            modelBuilder.Entity("GGData.Models.Estatistica", b =>
            {
                b.HasOne("GGData.Models.Jogo", "Jogo")
                    .WithOne("Estatistica")
                    .HasForeignKey("GGData.Models.Estatistica", "JogoId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Jogo");
            });

            modelBuilder.Entity("GGData.Models.Jogo", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Utilizador")
                    .WithMany()
                    .HasForeignKey("UtilizadorId");

                b.Navigation("Utilizador");
                b.Navigation("Avaliacoes");
                b.Navigation("Estatistica")
                    .IsRequired();
            });

            modelBuilder.Entity("GGData.Models.Usuarios", b =>
            {
                b.Navigation("Avaliacoes");
            });
#pragma warning restore 612, 618
        }
    }
}
